# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from DataJoin.common import proxy_data_pb2 as DataJoin_dot_common_dot_proxy__data__pb2


class ProxyDataServiceStub(object):
  """data transfer service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UnaryCall = channel.unary_unary(
        '/ProxyDataService/UnaryCall',
        request_serializer=DataJoin_dot_common_dot_proxy__data__pb2.Packet.SerializeToString,
        response_deserializer=DataJoin_dot_common_dot_proxy__data__pb2.Packet.FromString,
        )


class ProxyDataServiceServicer(object):
  """data transfer service
  """

  def UnaryCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProxyDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UnaryCall': grpc.unary_unary_rpc_method_handler(
          servicer.UnaryCall,
          request_deserializer=DataJoin_dot_common_dot_proxy__data__pb2.Packet.FromString,
          response_serializer=DataJoin_dot_common_dot_proxy__data__pb2.Packet.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ProxyDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
