# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from DataJoin.common import common_pb2 as fedlearner_dot_common_dot_common__pb2
from DataJoin.common import trainer_worker_service_pb2 as fedlearner_dot_common_dot_trainer__worker__service__pb2


class TrainerWorkerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Transmit = channel.unary_unary(
        '/fedlearner.common.TrainerWorkerService/Transmit',
        request_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerMessage.SerializeToString,
        response_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerResponse.FromString,
        )
    self.StreamTransmit = channel.stream_stream(
        '/fedlearner.common.TrainerWorkerService/StreamTransmit',
        request_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerMessage.SerializeToString,
        response_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerResponse.FromString,
        )
    self.LoadDataBlock = channel.unary_unary(
        '/fedlearner.common.TrainerWorkerService/LoadDataBlock',
        request_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.LoadDataBlockRequest.SerializeToString,
        response_deserializer=fedlearner_dot_common_dot_common__pb2.Status.FromString,
        )
    self.Connect = channel.unary_unary(
        '/fedlearner.common.TrainerWorkerService/Connect',
        request_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.ConnectRequest.SerializeToString,
        response_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.ConnectResponse.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/fedlearner.common.TrainerWorkerService/Heartbeat',
        request_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.HeartbeatRequest.SerializeToString,
        response_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.HeartbeatResponse.FromString,
        )


class TrainerWorkerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Transmit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamTransmit(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadDataBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrainerWorkerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Transmit': grpc.unary_unary_rpc_method_handler(
          servicer.Transmit,
          request_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerMessage.FromString,
          response_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerResponse.SerializeToString,
      ),
      'StreamTransmit': grpc.stream_stream_rpc_method_handler(
          servicer.StreamTransmit,
          request_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerMessage.FromString,
          response_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.TrainerWorkerResponse.SerializeToString,
      ),
      'LoadDataBlock': grpc.unary_unary_rpc_method_handler(
          servicer.LoadDataBlock,
          request_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.LoadDataBlockRequest.FromString,
          response_serializer=fedlearner_dot_common_dot_common__pb2.Status.SerializeToString,
      ),
      'Connect': grpc.unary_unary_rpc_method_handler(
          servicer.Connect,
          request_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.ConnectRequest.FromString,
          response_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.ConnectResponse.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.HeartbeatRequest.FromString,
          response_serializer=fedlearner_dot_common_dot_trainer__worker__service__pb2.HeartbeatResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fedlearner.common.TrainerWorkerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
