# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedlearner/common/trainer_master_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from DataJoin.common import common_pb2 as fedlearner_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fedlearner/common/trainer_master_service.proto',
  package='fedlearner.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.fedlearner/common/trainer_master_service.proto\x12\x11\x66\x65\x64learner.common\x1a\x1e\x66\x65\x64learner/common/common.proto\"9\n\x10\x44\x61taBlockRequest\x12\x13\n\x0bworker_rank\x18\x01 \x01(\r\x12\x10\n\x08\x62lock_id\x18\x02 \x01(\t\"G\n\rDataBlockInfo\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x11\n\tdata_path\x18\x02 \x01(\t\x12\x11\n\tmeta_path\x18\x03 \x01(\t\"y\n\x11\x44\x61taBlockResponse\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.fedlearner.common.Status\x12\x39\n\x0f\x64\x61ta_block_info\x18\x02 \x01(\x0b\x32 .fedlearner.common.DataBlockInfo2w\n\x14TrainerMasterService\x12_\n\x10RequestDataBlock\x12#.fedlearner.common.DataBlockRequest\x1a$.fedlearner.common.DataBlockResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[fedlearner_dot_common_dot_common__pb2.DESCRIPTOR,])




_DATABLOCKREQUEST = _descriptor.Descriptor(
  name='DataBlockRequest',
  full_name='fedlearner.common.DataBlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_rank', full_name='fedlearner.common.DataBlockRequest.worker_rank', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_id', full_name='fedlearner.common.DataBlockRequest.block_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=158,
)


_DATABLOCKINFO = _descriptor.Descriptor(
  name='DataBlockInfo',
  full_name='fedlearner.common.DataBlockInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='fedlearner.common.DataBlockInfo.block_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_path', full_name='fedlearner.common.DataBlockInfo.data_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta_path', full_name='fedlearner.common.DataBlockInfo.meta_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=231,
)


_DATABLOCKRESPONSE = _descriptor.Descriptor(
  name='DataBlockResponse',
  full_name='fedlearner.common.DataBlockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='fedlearner.common.DataBlockResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_block_info', full_name='fedlearner.common.DataBlockResponse.data_block_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=354,
)

_DATABLOCKRESPONSE.fields_by_name['status'].message_type = fedlearner_dot_common_dot_common__pb2._STATUS
_DATABLOCKRESPONSE.fields_by_name['data_block_info'].message_type = _DATABLOCKINFO
DESCRIPTOR.message_types_by_name['DataBlockRequest'] = _DATABLOCKREQUEST
DESCRIPTOR.message_types_by_name['DataBlockInfo'] = _DATABLOCKINFO
DESCRIPTOR.message_types_by_name['DataBlockResponse'] = _DATABLOCKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataBlockRequest = _reflection.GeneratedProtocolMessageType('DataBlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATABLOCKREQUEST,
  '__module__' : 'fedlearner.common.trainer_master_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.DataBlockRequest)
  })
_sym_db.RegisterMessage(DataBlockRequest)

DataBlockInfo = _reflection.GeneratedProtocolMessageType('DataBlockInfo', (_message.Message,), {
  'DESCRIPTOR' : _DATABLOCKINFO,
  '__module__' : 'fedlearner.common.trainer_master_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.DataBlockInfo)
  })
_sym_db.RegisterMessage(DataBlockInfo)

DataBlockResponse = _reflection.GeneratedProtocolMessageType('DataBlockResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATABLOCKRESPONSE,
  '__module__' : 'fedlearner.common.trainer_master_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.DataBlockResponse)
  })
_sym_db.RegisterMessage(DataBlockResponse)



_TRAINERMASTERSERVICE = _descriptor.ServiceDescriptor(
  name='TrainerMasterService',
  full_name='fedlearner.common.TrainerMasterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=356,
  serialized_end=475,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestDataBlock',
    full_name='fedlearner.common.TrainerMasterService.RequestDataBlock',
    index=0,
    containing_service=None,
    input_type=_DATABLOCKREQUEST,
    output_type=_DATABLOCKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINERMASTERSERVICE)

DESCRIPTOR.services_by_name['TrainerMasterService'] = _TRAINERMASTERSERVICE

# @@protoc_insertion_point(module_scope)
